#Redis se utiliza como sistema de caché y comunicación entre microservicios para mejorar el rendimiento y facilitar el intercambio de datos.
# Imagen base
FROM redis:latest

# Puerto que usará Redis 
EXPOSE 6379

# Configuración de Redis
CMD [ "redis-server"]
